let calc = require("./node3")
let v1 = new calc.circle(5)
let v2 = new calc.rectangle(5,5)
let v3 = new calc.triangle(5,5,5)
v1.calcAreaCircle()
v1.calcCircumference()
v1.calcDiameter()
v2.calcAreaRectangle()
v2.calcPerimeterRectangle()
v3.isEquilaterial()
v3.calcPerimeter()
